#!/usr/bin/env python3
"""
Download Google Fonts as self-hosted woff2s + CSS.

Output: public/fonts/{family}/{file}.woff2 + public/fonts/fonts.css

The Google Fonts CSS API serves @font-face rules with unicode-range
subsetting baked in (essential for CJK fonts like Noto Serif SC, which
gets split into ~100 small per-Unicode-block chunks). We fetch that CSS
with a modern Chrome UA, download every referenced woff2, and rewrite
the URLs to local /fonts/... paths so the site doesn't depend on
fonts.googleapis.com (blocked in mainland China).

Run: python3 scripts/fetch-fonts.py
"""

import os
import re
import sys
import urllib.request

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SITE_DIR = os.path.dirname(SCRIPT_DIR)
FONTS_DIR = os.path.join(SITE_DIR, "public", "fonts")
CSS_OUT = os.path.join(FONTS_DIR, "fonts.css")

# Union of fonts used across LandingLayout and ThesisLayout.
GOOGLE_CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,600;0,8..60,700;1,8..60,400"
    "&family=Noto+Serif+SC:wght@400;600;700"
    "&family=Source+Sans+3:wght@400;600"
    "&family=Noto+Sans+SC:wght@400"
    "&family=JetBrains+Mono:wght@400"
    "&display=swap"
)

# Modern Chrome UA so Google returns woff2 with full unicode-range subsetting.
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/124.0.0.0 Safari/537.36"
)

URL_RE = re.compile(r"url\((https://fonts\.gstatic\.com/[^)]+\.woff2)\)")


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req) as resp:
        return resp.read()


def local_rel(url):
    """Map fonts.gstatic.com/s/{family}/{ver}/{file} -> {family}/{file}."""
    m = re.match(r"https://fonts\.gstatic\.com/s/([^/]+)/[^/]+/(.+\.woff2)", url)
    if not m:
        raise ValueError(f"Unexpected font URL: {url}")
    return f"{m.group(1)}/{m.group(2)}"


def main():
    print("Fetching CSS from Google Fonts...")
    css = fetch(GOOGLE_CSS_URL).decode("utf-8")

    urls = URL_RE.findall(css)
    unique = sorted(set(urls))
    print(f"  {len(urls)} url() refs, {len(unique)} unique woff2 files")

    os.makedirs(FONTS_DIR, exist_ok=True)
    downloaded = skipped = 0
    total_bytes = 0
    for url in unique:
        rel = local_rel(url)
        out = os.path.join(FONTS_DIR, rel)
        os.makedirs(os.path.dirname(out), exist_ok=True)
        if os.path.exists(out):
            skipped += 1
            total_bytes += os.path.getsize(out)
            continue
        data = fetch(url)
        with open(out, "wb") as f:
            f.write(data)
        downloaded += 1
        total_bytes += len(data)
        print(f"  + {rel} ({len(data) // 1024} KB)")

    print(
        f"  downloaded {downloaded}, skipped {skipped} (already present); "
        f"total {total_bytes // 1024} KB on disk"
    )

    rewritten = URL_RE.sub(lambda m: f"url(/fonts/{local_rel(m.group(1))})", css)
    header = (
        "/* Generated by scripts/fetch-fonts.py from Google Fonts.\n"
        " * Edit by re-running the script, not by hand.\n"
        " */\n"
    )
    with open(CSS_OUT, "w") as f:
        f.write(header + rewritten)
    print(f"  wrote {CSS_OUT}")


if __name__ == "__main__":
    main()
